server:
  port: 9527

spring:
  application:
    name: springcloud-gateway

#注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
  instance:
    instance-id: spring-zuul
#zuul配置
zuul:
  routes:
    mydept:
      serviceId : springcloud-provider-dept
      path : /mydept/**
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  ignored-services: "*"
  prefix: /test
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000
#zuul routes 格式 Map<String, ZuulRoute> routes
#zuul:
#  routes:
#    feign-consumer-hello:
#      path: /feign-consumer/hello/**
#      serviceId: feign-consumer-hello
#  feign-consumer:
#      path: /feign-consumer/**
#      serviceId: feign-consumer